# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TestCli < Formula
  desc "A minimal CLI for testing release pipelines"
  homepage "https://github.com/martwebber/test-release-pipeline"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/martwebber/test-release-pipeline/releases/download/v1.0.2/test-release-pipeline_1.0.2_darwin_amd64.tar.gz"
      sha256 "46a3658b2303ba212947a2d25eeca98c93c5adf9c83b882914e73d01254415d8"

      def install
        bin.install "test-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/martwebber/test-release-pipeline/releases/download/v1.0.2/test-release-pipeline_1.0.2_darwin_arm64.tar.gz"
      sha256 "5b07946254313f082683cebdf096f866a6ce82ff23d436abec9645d2403e61fe"

      def install
        bin.install "test-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/martwebber/test-release-pipeline/releases/download/v1.0.2/test-release-pipeline_1.0.2_linux_amd64.tar.gz"
      sha256 "034fd884efb4ef22bbe1d69c238c24fd46de5839bb15beb4561fd91f976ea3b7"
      def install
        bin.install "test-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/martwebber/test-release-pipeline/releases/download/v1.0.2/test-release-pipeline_1.0.2_linux_arm64.tar.gz"
      sha256 "f87b7fe27eb9fa2db735fa49ea67ba28dcfa74780b87ebbd3db7fb0b3c767232"
      def install
        bin.install "test-cli"
      end
    end
  end

  test do
    system "#{bin}/test-cli --version"
  end
end
