# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MpesaCli < Formula
  desc "A command-line interface for M-Pesa API operations"
  homepage "https://github.com/martwebber/mpesa-cli"
  version "1.1.0"
  license "MIT"

  depends_on "go" => :optional
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/martwebber/mpesa-cli/releases/download/v1.1.0/mpesa-cli_Linux_x86_64.tar.gz"
    sha256 "26b3e8e938105927c90bcc1bf66fa4257c9aa4e7b23b0cde62828305ea14d333"
    def install
      bin.install "mpesa-cli"

      # Install shell completions
      bash_completion.install "completions/mpesa-cli.bash" => "mpesa-cli"
      zsh_completion.install "completions/mpesa-cli.zsh" => "_mpesa-cli"
      fish_completion.install "completions/mpesa-cli.fish"
    end
  end
  if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/martwebber/mpesa-cli/releases/download/v1.1.0/mpesa-cli_Linux_armv6.tar.gz"
    sha256 "201676790cdcb3475c87e082f233b668d2cbac12fc20e981abecff884be4143b"
    def install
      bin.install "mpesa-cli"

      # Install shell completions
      bash_completion.install "completions/mpesa-cli.bash" => "mpesa-cli"
      zsh_completion.install "completions/mpesa-cli.zsh" => "_mpesa-cli"
      fish_completion.install "completions/mpesa-cli.fish"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/martwebber/mpesa-cli/releases/download/v1.1.0/mpesa-cli_Linux_arm64.tar.gz"
    sha256 "e1ba682e1b35463479eadc632513f8c3c464f81bcb9b53ad7fd8a7ce5b66d48b"
    def install
      bin.install "mpesa-cli"

      # Install shell completions
      bash_completion.install "completions/mpesa-cli.bash" => "mpesa-cli"
      zsh_completion.install "completions/mpesa-cli.zsh" => "_mpesa-cli"
      fish_completion.install "completions/mpesa-cli.fish"
    end
  end

  test do
    system "#{bin}/mpesa-cli", "version"
  end
end
