# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MpesaCli < Formula
  desc "A command-line interface for M-Pesa API operations"
  homepage "https://github.com/martwebber/mpesa-cli"
  version "1.1.3"
  license "MIT"

  depends_on "go" => :optional
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/martwebber/mpesa-cli/releases/download/v1.1.3/mpesa-cli_Linux_x86_64.tar.gz"
    sha256 "8b311473f0f86dc3a4ec9d5c1ae85efc9cb8cac79c57c45edbffcd9b7a0c5202"
    def install
      bin.install "mpesa-cli"

      # Install shell completions
      bash_completion.install "completions/mpesa-cli.bash" => "mpesa-cli"
      zsh_completion.install "completions/mpesa-cli.zsh" => "_mpesa-cli"
      fish_completion.install "completions/mpesa-cli.fish"
    end
  end
  if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/martwebber/mpesa-cli/releases/download/v1.1.3/mpesa-cli_Linux_armv6.tar.gz"
    sha256 "915b6d91743eb5453a0f3d70009f21c8ed69857c15442da30bc48693e6103f77"
    def install
      bin.install "mpesa-cli"

      # Install shell completions
      bash_completion.install "completions/mpesa-cli.bash" => "mpesa-cli"
      zsh_completion.install "completions/mpesa-cli.zsh" => "_mpesa-cli"
      fish_completion.install "completions/mpesa-cli.fish"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/martwebber/mpesa-cli/releases/download/v1.1.3/mpesa-cli_Linux_arm64.tar.gz"
    sha256 "af6e072c96709a501da471a6f3341698ea7089214c94bc3f1cab3844a1cf788d"
    def install
      bin.install "mpesa-cli"

      # Install shell completions
      bash_completion.install "completions/mpesa-cli.bash" => "mpesa-cli"
      zsh_completion.install "completions/mpesa-cli.zsh" => "_mpesa-cli"
      fish_completion.install "completions/mpesa-cli.fish"
    end
  end

  test do
    system "#{bin}/mpesa-cli", "version"
  end
end
