# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MpesaCli < Formula
  desc "A command-line interface for M-Pesa API operations"
  homepage "https://github.com/martwebber/mpesa-cli"
  version "1.0.23"
  license "MIT"

  depends_on "go" => :optional
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/martwebber/mpesa-cli/releases/download/v1.0.23/mpesa-cli_Linux_x86_64.tar.gz"
    sha256 "daa60450368a44d865213946c5990347ad2ee53287b7b20b769685b95a41bb0d"
    def install
      bin.install "mpesa-cli"

      # Install shell completions
      bash_completion.install "completions/mpesa-cli.bash" => "mpesa-cli"
      zsh_completion.install "completions/mpesa-cli.zsh" => "_mpesa-cli"
      fish_completion.install "completions/mpesa-cli.fish"
    end
  end
  if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/martwebber/mpesa-cli/releases/download/v1.0.23/mpesa-cli_Linux_armv6.tar.gz"
    sha256 "cd2f7a5500610f1adeafb0ba128354ab88269f0c8953fb8cc2e4f869566d9c89"
    def install
      bin.install "mpesa-cli"

      # Install shell completions
      bash_completion.install "completions/mpesa-cli.bash" => "mpesa-cli"
      zsh_completion.install "completions/mpesa-cli.zsh" => "_mpesa-cli"
      fish_completion.install "completions/mpesa-cli.fish"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/martwebber/mpesa-cli/releases/download/v1.0.23/mpesa-cli_Linux_arm64.tar.gz"
    sha256 "be0424418b4e25b3f73f7cb7c36a5afe280bdab2f22ee9f9a1c3f9c9b9260989"
    def install
      bin.install "mpesa-cli"

      # Install shell completions
      bash_completion.install "completions/mpesa-cli.bash" => "mpesa-cli"
      zsh_completion.install "completions/mpesa-cli.zsh" => "_mpesa-cli"
      fish_completion.install "completions/mpesa-cli.fish"
    end
  end

  test do
    system "#{bin}/mpesa-cli", "version"
  end
end
